### PR TITLE
AUFS changes

### PR DESCRIPTION
**Pull request by odra**
Hi,

Host machines that use the AUFS storage driver for docker fail to install the android sdk "tools" package (actually it fails to rename the temp tools folder back to its original name) so the tools folder stays empty and it can't proceed with the installation/image building.

I have added a small change where it tries to unzip all zip files from the temp folder into the android home folder (it ignores any errors while doing that so it won't break builds for other storage drivers that do not have this problem).

Also added the build-tools 23.0.2 (I can remove this one if you want to).

### CODE REVIEW

**Comment by jacek-marchwicki** [comment]
Thanks for contribution. I'll see your changes tomorrow

**Comment by jacek-marchwicki** [comment]
@odra Are you sure that this change is required to build this image on AUFS file system?
I just build and image on my notebook with aufs:

``` bash
docker info
```

```
 Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 48
 Dirperm1 Supported: true
```

Here is a log:
[log.txt](https://github.com/appunite/docker/files/486549/log.txt)

I think your change solving issue that appear before installing tools was merged to single line:

``` docker
RUN cd /opt && wget --output-document=android-sdk.tgz --quiet http://dl.google.com/android/android-sdk_r24.1.2-linux.tgz && \
  tar xzf android-sdk.tgz && \
  rm -f android-sdk.tgz && \
  chown -R root.root android-sdk-linux && \
  /opt/tools/android-accept-licenses.sh "android-sdk-linux/tools/android update sdk --all --no-ui --filter platform-tools,tools" && \
  /opt/tools/android-accept-licenses.sh "android-sdk-linux/tools/android update sdk --all --no-ui --filter platform-tools,tools,build-tools-22.0.1,android-22,addon-google_apis_x86-google-22,extra-android-support,extra-android-m2repository,extra-google-m2repository,sys-img-armeabi-v7a-android-22"
```

I think problem only appeared when AUFS tried to save state between executions of `tar xzf android-sdk.tgz` and `/opt/tools/android-accept-licenses.sh "...."`.

Can you provide your logs?

**Comment by odra** [comment]
Interesting I used to have this issue when building in AUFS after installing the "tools" package:

```
Failed to rename directory /opt/android-sdk-linux/tools to /opt/android-sdk-linux/temp/ToolPackage.old01.

Failed to create directory /opt/android-sdk-linux/tools
```

I guess it was fixed in this commit? [4b81bef90c6ec0a4e4d47e5433b170e696cdd8cd](https://github.com/appunite/docker/commit/4b81bef90c6ec0a4e4d47e5433b170e696cdd8cd)

**Comment by jacek-marchwicki** [comment]
@odra this change was introduced to fix an issue https://github.com/appunite/docker/commit/41a0daed37106afe1ab6996f2596ed1a9e810d15

btw: all images are on docker-hub https://hub.docker.com/r/jacekmarchwicki/android/tags/

**Comment by odra** [comment]
@jacek-marchwicki Cool, I will close the PR since it is working for me now :)

Thanks!

**Pull request closed without merging**
